package app.lusk.virga.feature.explorer

import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.Surface
import androidx.compose.ui.Modifier
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.junit4.v2.createComposeRule
import androidx.compose.ui.test.onNodeWithText
import androidx.compose.ui.test.onRoot
import app.lusk.virga.core.common.dispatchers.DispatcherProvider
import app.lusk.virga.core.common.model.FileItem
import app.lusk.virga.core.common.model.Remote
import app.lusk.virga.core.data.FileBrowserRepository
import app.lusk.virga.core.data.RemoteFolderPickStore
import app.lusk.virga.core.data.RemoteRepository
import app.lusk.virga.core.designsystem.theme.VirgaTheme
import com.github.takahirom.roborazzi.RoborazziRule
import com.github.takahirom.roborazzi.captureRoboImage
import io.mockk.coEvery
import io.mockk.every
import io.mockk.mockk
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.flowOf
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import org.robolectric.annotation.GraphicsMode

/**
 * Roborazzi render tests for PullToRefreshBox hosting and the properties sheet.
 *
 * Each test exercises a distinct state:
 *  - Pull-to-refresh host: the file list renders inside PullToRefreshBox.
 *  - Properties sheet: a file with size + mimeType + modTime; a directory shows "Folder" and "—".
 *  - Null modTime: "—" for the modified row.
 *
 * Goldens are generated by:
 *   ./gradlew :feature:explorer:recordRoborazziDebug
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34], qualifiers = "w360dp-h640dp-normal-long-notround-any-420dpi-keyshidden-nonav")
@GraphicsMode(GraphicsMode.Mode.NATIVE)
class FileBrowserPropertiesScreenTest {

    @get:Rule
    val composeRule = createComposeRule()

    @get:Rule
    val roborazziRule = RoborazziRule(
        composeRule = composeRule,
        captureRoot = composeRule.onRoot(),
        options = RoborazziRule.Options(
            outputDirectoryPath = "src/test/snapshots",
        ),
    )

    private val fixedModTime = 1_609_459_200_000L

    private val populatedListing = listOf(
        FileItem(name = "Photos", path = "Photos", isDir = true, size = 0, modTimeEpochMs = fixedModTime),
        FileItem(name = "report.pdf", path = "report.pdf", isDir = false, size = 245_760, modTimeEpochMs = fixedModTime),
    )

    private fun viewModel(listing: List<FileItem>): FileBrowserViewModel {
        val fileBrowser: FileBrowserRepository = mockk(relaxed = true) {
            coEvery { list(any(), any()) } returns listing
        }
        val remoteRepo: RemoteRepository = mockk(relaxed = true) {
            every { remotes } returns flowOf(listOf(Remote("gdrive", "drive")))
        }
        val dispatchers: DispatcherProvider = mockk(relaxed = true) {
            every { main } returns Dispatchers.Unconfined
            every { default } returns Dispatchers.Unconfined
            every { io } returns Dispatchers.Unconfined
        }
        return FileBrowserViewModel(fileBrowser, remoteRepo, dispatchers, RemoteFolderPickStore())
    }

    // -------------------------------------------------------------------------
    // Pull-to-refresh host
    // -------------------------------------------------------------------------

    @Test
    fun pullToRefreshBox_hostsFileList() {
        val vm = viewModel(populatedListing)
        vm.selectRemote("gdrive")
        composeRule.setContent {
            VirgaTheme {
                Surface(modifier = Modifier.fillMaxSize()) {
                    FileBrowserScreen(onBack = {}, viewModel = vm)
                }
            }
        }
        composeRule.waitForIdle()
        // Verify that both entries are rendered inside the PullToRefreshBox.
        composeRule.onNodeWithText("Photos").assertIsDisplayed()
        composeRule.onNodeWithText("report.pdf").assertIsDisplayed()
        composeRule.onRoot().captureRoboImage()
    }

    // -------------------------------------------------------------------------
    // Properties sheet — file with size, mimeType, and modTime
    // -------------------------------------------------------------------------

    @Test
    fun propertiesSheet_fileWithMimeAndModTime() {
        val item = FileItem(
            name = "budget.xlsx",
            path = "docs/budget.xlsx",
            isDir = false,
            size = 98_765,
            modTimeEpochMs = fixedModTime,
            mimeType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )
        captureRoboImage(
            filePath = "src/test/snapshots/" +
                "app.lusk.virga.feature.explorer.FileBrowserPropertiesScreenTest." +
                "propertiesSheet_fileWithMimeAndModTime.png",
        ) {
            VirgaTheme {
                Surface(modifier = Modifier.fillMaxSize()) {
                    PropertiesContent(item = item)
                }
            }
        }
        composeRule.setContent {
            VirgaTheme {
                Surface(modifier = Modifier.fillMaxSize()) {
                    PropertiesContent(item = item)
                }
            }
        }
        composeRule.waitForIdle()
        composeRule.onNodeWithText("budget.xlsx").assertIsDisplayed()
        composeRule.onNodeWithText("docs/budget.xlsx").assertIsDisplayed()
        // Derive expected size text from the same formatter so the assertion isn't locale-fragile.
        composeRule.onNodeWithText(app.lusk.virga.core.common.util.formatFileSize(item.size)).assertIsDisplayed()
    }

    // -------------------------------------------------------------------------
    // Properties sheet — directory shows "Folder" type and "—" for size
    // -------------------------------------------------------------------------

    @Test
    fun propertiesSheet_directoryShowsFolderAndDash() {
        val item = FileItem(
            name = "Photos",
            path = "Photos",
            isDir = true,
            size = 0,
            modTimeEpochMs = fixedModTime,
        )
        composeRule.setContent {
            VirgaTheme {
                Surface(modifier = Modifier.fillMaxSize()) {
                    PropertiesContent(item = item)
                }
            }
        }
        composeRule.waitForIdle()
        composeRule.onNodeWithText("Folder").assertIsDisplayed()
        // "—" appears for the size row (directory has no size).
        composeRule.onNodeWithText("—").assertIsDisplayed()
        composeRule.onRoot().captureRoboImage()
    }

    // -------------------------------------------------------------------------
    // Properties sheet — null modTime shows "—"
    // -------------------------------------------------------------------------

    @Test
    fun propertiesSheet_nullModTimeShowsDash() {
        val item = FileItem(
            name = "notes.txt",
            path = "notes.txt",
            isDir = false,
            size = 1024,
            modTimeEpochMs = null,
        )
        composeRule.setContent {
            VirgaTheme {
                Surface(modifier = Modifier.fillMaxSize()) {
                    PropertiesContent(item = item)
                }
            }
        }
        composeRule.waitForIdle()
        // "—" appears for the modified row (modTimeEpochMs is null).
        composeRule.onNodeWithText("—").assertIsDisplayed()
        composeRule.onRoot().captureRoboImage()
    }
}
